branch-defaults:
  mike-eb:
    environment: fast-track
    group_suffix: null
  mike-ft:
    environment: null
    group_suffix: null
global:
  application_name: fast_track_chat
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
container_commands:
  enable_websockets:
    command: "sed -i '/\\s*proxy_set_header\\s*Connection/c \\\n         proxy_set_header\
      \ Upgrade $http_upgrade;\\\n         proxy_set_header Connection \"upgrade\"\
      ;\\\n ' /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf"