branch-defaults:
  mike-eb:
    environment: fast-track
    group_suffix: null
  mike-ft:
    environment: null
    group_suffix: null
global:
  application_name: fast_track_chat
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
  files:
    /etc/nginx/conf.d/proxy.conf:
      mode: "000644"
      owner: root
      group: root
      content: |
        upstream nodejs {
          server 127.0.0.1:8081;
          keepalive 256;
        }

        server {
          client_max_body_size 500M;
          listen 8080;
          server_name  download.yourdomain.com;

          if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})T(\d{2})") {
              set $year $1;
              set $month $2;
              set $day $3;
              set $hour $4;
          }
          access_log /var/log/nginx/healthd/application.log.$year-$month-$day-$hour healthd;
          access_log  /var/log/nginx/access.log  main;

          location / {
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_set_header X-NginX-Proxy true;

              proxy_pass http://127.0.0.1:8081/;
              proxy_redirect off;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }

          gzip on;
          gzip_comp_level 4;
          gzip_types text/html text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

          location /static {
              alias /var/app/current/static;
          }
        }
  container_commands:
   removeconfig:
      command: "rm -f /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf"